name: maya_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.5.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  intl: null
  timeago: ^3.7.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
