// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPBoMNUQ2qMjg4h4Tyo10rBJKPirxzSHk',
    appId: '1:658568950794:web:4a24ea6642a0007eecdbf3',
    messagingSenderId: '658568950794',
    projectId: 'maya-flutter-bf071',
    authDomain: 'maya-flutter-bf071.firebaseapp.com',
    storageBucket: 'maya-flutter-bf071.firebasestorage.app',
    measurementId: 'G-YWYFML6DX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfcWvC4yKt6YNFRsyt5CxhGx0tYZ76ESw',
    appId: '1:658568950794:android:a119bb5ff6b7dfbbecdbf3',
    messagingSenderId: '658568950794',
    projectId: 'maya-flutter-bf071',
    storageBucket: 'maya-flutter-bf071.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHayQmQ6cgiZHg0Z_cO7E59iP8C8ZQZwk',
    appId: '1:658568950794:ios:f58b7778d23b0272ecdbf3',
    messagingSenderId: '658568950794',
    projectId: 'maya-flutter-bf071',
    storageBucket: 'maya-flutter-bf071.firebasestorage.app',
    iosBundleId: 'com.example.mayaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHayQmQ6cgiZHg0Z_cO7E59iP8C8ZQZwk',
    appId: '1:658568950794:ios:f58b7778d23b0272ecdbf3',
    messagingSenderId: '658568950794',
    projectId: 'maya-flutter-bf071',
    storageBucket: 'maya-flutter-bf071.firebasestorage.app',
    iosBundleId: 'com.example.mayaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPBoMNUQ2qMjg4h4Tyo10rBJKPirxzSHk',
    appId: '1:658568950794:web:d02b6f28ca7dd94decdbf3',
    messagingSenderId: '658568950794',
    projectId: 'maya-flutter-bf071',
    authDomain: 'maya-flutter-bf071.firebaseapp.com',
    storageBucket: 'maya-flutter-bf071.firebasestorage.app',
    measurementId: 'G-K17KQKGBB7',
  );
}